ROBOT_MIN = 2
ROBOT_MAX = 30
ROBOT_COST_FOOS = 6
ROBOT_COST_EUROS = 3
ROBOT_CHANGE_ACTIVITY_TIME = 5

FOO_MINING_TIME = 1
BAR_MINING_TIME_MIN = 0.5
BAR_MINING_TIME_MAX = 2

FOOBAR_ASSEMBLY_TIME = 2
FOOBAR_ASSEMBLY_SUCCESS_RATE = 0.6
FOOBAR_SELL_MAX = 5
FOOBAR_SELL_TIME = 10
FOOBAR_SELL_PRICE = 1

DURATION_MODIFIER = 0.01